# Generated by Django 4.1.1 on 2022-09-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0002_remove_super_primary_ability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='super',
            name='image',
            field=models.ImageField(null=True, upload_to='super_uploads/'),
        ),
    ]
